spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.5:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
env: test6
girl:
  name: lily
  age: 20
